#!/bin/bash

# Define an array of repositories
repositories=(
  "WeatherForecast"
  "spring-boot-newrelic"
  "terraform-k8s-jenkins"
  "jenkins-api"
  "jenkins-api-postman-tests"
  "roadmaps"
  "getting-started-app"
  "labs-devops-challenges"
  "robot-friend"
  "marublaize"
  "Datapi-DevOps-Challenge"
  "rede-cnpj"
  "mysql-ansible"
  "exemplo-jean"
  "terraform-kubernetes"
  "k3s-minio-deployment"
  "lwps"
  "terraform-aws-ecs-web-app"
  "terraform-aws-cloudfront-s3-cdn"
  "terraform-aws-ecs-cloudwatch-sns-alarms"
  "terraform-aws-ecs-alb-service-task"
  "terraform-aws-efs"
  "terraform-aws-ecs-cluster"
  "terraform-aws-step-functions"
  "terraform-aws-ecs-codepipeline"
  "devops-challenge-20221219"
  "lw-go-scripts"
  "node-toy-scrape"
  "desafio-devops"
  "devops-assessment"
  "deploy-to-s3-leo"
  "simpleapp-python"
  "zabbix-docker"
  "terraform-tls-ssh-key-pair"
  "nginx-dynatrace"
  "telefonica-vivo-brasil-demo2"
  "telefonica-vivo-brasil-demo"
  "sql_conn"
  "express-cosmosdb"
  "nr-ext-api-test"
  "up-and-running-jenkins"
  "fourkeys"
  "prom-grafana-demo"
  "debian-nginx-demo"
  "terraform-modules"
  "linux-tips-and-tricks"
  "devops"
  "pure-bash-bible"
  "tmagalhaes.com.br"
  "desafios"
  "nodejs-posgresql"
  "desafio"
  "terraform-reference-architectures"
  "dockerfiles"
  "arch-setup"
  "microk8s-aws"
  "k3s-ansible"
  "ansible-kubernetes-ha-cluster"
  "php-fpm"
)

# Loop through each repository and import it
for repo in "${repositories[@]}"; do
  echo "Importing repository: $repo"
  terraform import "github_repository.repos[\"$repo\"]" "$repo"
done
